import {
  PaintRoller,
  Paintbrush,
  Brush,
  SprayCan,
  Droplet,
  Layers,
  Wrench,
  Hammer,
  Ruler,
  Home,
  Building2,
  DoorOpen,
  Fence,
  TreePine,
  Car,
  Warehouse,
  ShowerHead,
  Lightbulb,
  Sparkles,
  Sun,
  Package,
  Grid3x3,
  Tag,
  Palette,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  roller: PaintRoller,
  brush: Paintbrush,
  brush2: Brush,
  spray: SprayCan,
  droplet: Droplet,
  palette: Palette,
  layers: Layers,
  wrench: Wrench,
  hammer: Hammer,
  ruler: Ruler,
  home: Home,
  building: Building2,
  door: DoorOpen,
  fence: Fence,
  tree: TreePine,
  car: Car,
  warehouse: Warehouse,
  shower: ShowerHead,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  sun: Sun,
  package: Package,
  grid: Grid3x3,
  tag: Tag,
};

export function categoryIcon(icone: string): LucideIcon {
  return CATEGORY_ICONS[icone] ?? Package;
}
